apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: functions
  name: functions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: functions
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: functions
    spec:
      containers:
        - args:
            - start
            - --main-service
            - /home/deno/functions/main
          env:
            - name: JWT_SECRET
              value: your-super-secret-jwt-token-with-at-least-32-characters-long
            - name: SUPABASE_ANON_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
            - name: SUPABASE_DB_URL
              value: postgresql://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres
            - name: SUPABASE_SERVICE_ROLE_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
            - name: SUPABASE_URL
              value: http://kong:8000
            - name: VERIFY_JWT
              value: "false"
          image: supabase/edge-runtime:v1.67.4
          name: supabase-edge-functions
      restartPolicy: Always
